############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Services"
url = "/services"
weight = 3

[[main]]
parent = "Services"
name = "Website Development"
url = "/services/website-development"
weight = 1

[[main]]
parent = "Services"
name = "MVP Development"
url = "/services/mvp-development"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 4

[[main]]
name = "Contact"
url = "/contact"
weight = 5


# footer menu

[[footer]]
name = "Blog"
url = "/blog"
weight = 1

[[footer]]
name = "Contact"
url = "/contact"
weight = 2

[[footer]]
name = "Website Development"
url = "/services/website-development"
weight = 3

[[footer]]
name = "MVP Development"
url = "/services/mvp-development"
weight = 4

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 5

